name: File Maker

on: push

env:
  REPO_URL: https://github.com/zerotier/ZeroTierOne/tree/dev
  IDENTITY_FILE: identity.public
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/centos:7.6.1810
    steps:
    - name: Checkout
      uses: actions/checkout@v2    

    - name: Start SSH via tmate
      uses: rdp-studio/ssh2actions@main
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    
    
