name: File Maker

on: push

env:
  REPO_URL: https://github.com/zerotier/ZeroTierOne/tree/dev
  IDENTITY_FILE: identity.public
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/centos:7.6.1810
    steps:
    - name: Checkout
      uses: actions/checkout@main  
      
    - name: Install 
      run: |
        yum install openssh

    - name: SSH to Actions
      uses: rdp-studio/ssh2actions@v2.0.0
    
    
