name: File Maker

env:
  REPO_URL: https://github.com/zerotier/ZeroTierOne/tree/dev
  IDENTITY_FILE: identity.public
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/centos:7.6.1810
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialization environment
      run: |
        yum install wget gcc gcc-c++ git -y
        yum install json-devel -y

    - name: Clone Zerotier source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL zerotier
        ln -sf /workdir/zerotier $GITHUB_WORKSPACE/zerotier
    - name: Read IDENTITY_FILE
      run: |
        [ -e $IDENTITY_FILE ] && mv $IDENTITY_FILE zerotier/identity.public

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
